# Nội dung file cloud/w9/exercise/apps/app-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application       # Root App đọc chữ này để biết đây là 1 App con
metadata:
  name: frontend-dev    # Tên sẽ hiển thị trên giao diện Argo CD
  namespace: argocd
spec:
  source:
    repoURL: 'https://github.com/NguyenKhanhDuy2703/nguyen-khanh-duy-aws-accelerator-p2.git'
    targetRevision: main
    path: CICD_repo/BE
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev-namespace
 
    