apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: fullstack-namespace
  labels:
    release: kube-prometheus-stack
    app: backend
    prometheus: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scheme: http