apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-monitor
  namespace: fullstack-namespace
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - fullstack-namespace
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http
      path: /metrics
      interval: 15s