apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd-metrics
  namespace: monitoring
  labels:
    release: prometheus # Giữ nguyên nhãn chuẩn mà bạn đã tìm ra
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: argocd # Đổi sang nhãn chung này để gom tất cả
  namespaceSelector:
    matchNames:
      - argocd
  endpoints:
    - port: metrics