apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: hello-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80