apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-manager
  namespace: argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io 
spec:
  project: default
  source:
    repoURL: 'https://github.com/NguyenKhanhDuy2703/nguyen-khanh-duy-aws-accelerator-p2.git'
    targetRevision: HEAD
    path: CICD_repo/argocd/apps 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    