apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-manager
  namespace: argocd # Root App PHẢI nằm trong namespace của ArgoCD
  finalizers:
    - resources-finalizer.argocd.argoproj.io # Giúp dọn dẹp sạch sẽ nếu bạn xóa Root App
spec:
  project: default
  source:
    repoURL: 'https://github.com/NguyenKhanhDuy2703/nguyen-khanh-duy-aws-accelerator-p2.git'
    targetRevision: HEAD
    path: CICD_repo/argocd/apps 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd # BẮT BUỘC: Vì các App con bản chất cũng là tài nguyên của ArgoCD, nên nó phải được đẻ ra ở đây.
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    