name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  # Job Build FE
  build-frontend:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    # Chỉ chạy job này nếu có file trong thư mục FE bị thay đổi
    if: paths: ['CICD_repo/FE/**'] 
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push FE
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }} ./CICD_repo/FE
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
      - name: Update FE manifest
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}|g" ./CICD_repo/FE/deployment.yaml
          # (Thêm lệnh git commit & push ở đây)

  # Job Build BE
  build-backend:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    # Chỉ chạy job này nếu có file trong thư mục BE bị thay đổi
    if: paths: ['CICD_repo/BE/**']
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push BE
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }} ./CICD_repo/BE
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
      - name: Update BE manifest
        run: |
          sed -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}|g" ./CICD_repo/BE/deployment.yaml
          # (Thêm lệnh git commit & push ở đây)