apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: backend-success-rate
  namespace: fullstack-namespace
spec:
  args:
  - name: service-name
  metrics:
  # Metric 1: Success Rate phải >= 95%
  - name: success-rate
    interval: 10s
    count: 5
    successCondition: result >= 0.95
    failureLimit: 3
    consecutiveErrorLimit: 4
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring:9090
        query: |
          (
            sum(rate(flask_http_request_total{job="{{args.service-name}}",status!~"5.."}[1m]))
            /
            sum(rate(flask_http_request_total{job="{{args.service-name}}"}[1m]))
          ) or on() vector(1)
  
  # Metric 2: P95 Latency phải < 1 giây
  - name: latency-p95
    interval: 10s
    count: 5
    successCondition: result < 1.0
    failureLimit: 3
    consecutiveErrorLimit: 4
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring:9090
        query: |
          (
            histogram_quantile(0.95,
              sum(rate(flask_http_request_duration_seconds_bucket{job="{{args.service-name}}"}[1m])) by (le)
            )
          ) or on() vector(0)
  
  # Metric 3: Pod phải Ready
  - name: pod-ready
    interval: 10s
    count: 5
    successCondition: result >= 1
    failureLimit: 3
    consecutiveErrorLimit: 4
    provider:
      prometheus:
        address: http://kube-prometheus-stack-prometheus.monitoring:9090
        query: |
          count(kube_pod_status_ready{namespace="fullstack-namespace",condition="true",pod=~"backend-rollout-.*"}) or on() vector(0)
